name: Deploy GameCorner to GitHub Pages

on:
  push:
    branches: [ main ]
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 8.0.x

      - name: Cache NuGet
        uses: actions/cache@v4
        with:
          path: ~/.nuget/packages
          key: ${{ runner.os }}-nuget-${{ hashFiles('**/*.csproj') }}
          restore-keys: |
            ${{ runner.os }}-nuget-

      - name: Publish Blazor WASM
        run: dotnet publish src/GameCorner/GameCorner.csproj -c Release -o out

      # Adjust <base href> for GitHub Pages (/<repo-name>/)
      - name: Fix base href for Pages
        run: |
          REPO="/${{ github.event.repository.name }}/"
          INDEX="out/wwwroot/index.html"
          sed -i "s|<base href=\"/\"|<base href=\"${REPO}\"|g" "$INDEX"

      # SPA fallback so deep-links work on Pages
      - name: Add SPA 404 fallback
        run: cp out/wwwroot/index.html out/wwwroot/404.html

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: out/wwwroot

  deploy:
    needs: build
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - id: deployment
        uses: actions/deploy-pages@v4